"""
Signature verification utilities for Zalo Mini App webhooks.

This module provides functions to generate and verify signatures for
webhook events from Zalo Mini App API.

Reference: https://miniapp.zaloplatforms.com/documents/open-apis/partner/verify-signature/
"""

import hashlib
import json
from typing import Any, Dict


class VerifySignature:
    """
    Utility class for generating and verifying webhook signatures.

    Reference: https://miniapp.zaloplatforms.com/documents/open-apis/partner/verify-signature/
    """

    @staticmethod
    def generate_signature(data: Any, api_key: str) -> str:
        """
        Generate signature for webhook data verification.

        The signature is generated by:
        1. Sorting all field names in the data alphabetically (A-Z)
        2. Building a content string with values in the sorted order
        3. Computing SHA256 hash of (content + API Key)

        Reference: https://miniapp.zaloplatforms.com/documents/open-apis/partner/verify-signature/

        Args:
            data: Dictionary containing webhook data with a 'timestamp' field
            api_key: Your Partner API Key provided by Zalo Mini App

        Returns:
            Hexadecimal string representing the SHA256 signature

        Raises:
            ValueError: If data is not a dict or timestamp is invalid
            RuntimeError: If signature generation fails

        Example:
            >>> from zmp_openapi.verify_signature import VerifySignature
            >>> data = {"timestamp": 1234567890, "event": "app_review", "status": "approved"}
            >>> signature = VerifySignature.generate_signature(data, "your_api_key")
            >>> # Compare with signature from webhook header
            >>> header_signature = request.headers.get("X-Signature")
            >>> if signature == header_signature:
            ...     print("Signature verified successfully")
        """
        try:
            if not isinstance(data, dict):
                raise ValueError("Data must be an object")
            if data.get("timestamp", 0) < 0:
                raise ValueError("Timestamp invalid")

            keys = sorted(data.keys())
            content_parts = []
            for key in keys:
                value = data[key]
                if isinstance(value, (dict, list)):
                    value = json.dumps(value, separators=(",", ":"), ensure_ascii=False)
                content_parts.append(str(value))

            content = "".join(content_parts)
            signature = hashlib.sha256(f"{content}{api_key}".encode("utf-8")).hexdigest()
            return signature
        except Exception as exc:
            error = RuntimeError(str(exc))
            error.args = (str(exc),)
            raise error
